//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POCS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1\r\n")]
        public string margin_bottom {
            get {
                return ((string)(this["margin_bottom"]));
            }
            set {
                this["margin_bottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9\r\n")]
        public string margin_left {
            get {
                return ((string)(this["margin_left"]));
            }
            set {
                this["margin_left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7\r\n")]
        public string margin_right {
            get {
                return ((string)(this["margin_right"]));
            }
            set {
                this["margin_right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.1\r\n")]
        public string margin_top {
            get {
                return ((string)(this["margin_top"]));
            }
            set {
                this["margin_top"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp")]
        public string strFileUploadPath {
            get {
                return ((string)(this["strFileUploadPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:2238/FileUploader.asmx")]
        public string FileUploaderService {
            get {
                return ((string)(this["FileUploaderService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Upon acceptance of this PO, Vendor agrees to our standard terms and conditions (attached) and we shall be entitled to treat any other terms and conditions introduced by or on behalf of the vendor as having no effect. 
Payment Terms : days from receipt of undisputed invoice supported by complete documentation 
Deliver to: Attn:  
Unless otherwise indicated on this PO, price includes delivery up to the delivery point mentioned above. 
Promised delivery date : ")]
        public string StdDeliveryInfo {
            get {
                return ((string)(this["StdDeliveryInfo"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>P/O No. and Project / CC Name (above) should be indicated on all Delivery Order and Invoice.</string>
  <string>The duration indicated above is an estimate only. Rental or charges shall based on the actual duration as per timesheet duly approved by TLO. Any duration in excess of the above estimaed shall require an Addendum to this P/O, Signed by the TLO authorised signatory.</string>
  <string>The Quantity indicated above is an estimate only. Invoice shall be based on the actual delivered quantity as per Delivery Order (DO) or Bunker Delivery Note (BDN). </string>
  <string>Bills of Loading or Airway bills must be attached to Invoice to support any freight charges charged</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ImportantInstructions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ImportantInstructions"]));
            }
            set {
                this["ImportantInstructions"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=POCS;Persist Security Info=True;User ID=sa;Password" +
            "=skinhead")]
        public string POS_DBConnectionString {
            get {
                return ((string)(this["POS_DBConnectionString"]));
            }
        }
    }
}
